### ISSUE TITLE
Mobile editors issues

### ISSUE THREAD

**Issue by aaronraimist** [standardnotes/mobile#53]
- [ ] GBoard swipe keyboard doesn't work with the advanced markdown editor, it just shows the first letter.
- [ ] Emoji don't appear properly in the advanced markdown editor
- [x] I would really like the option to set a different default editor on mobile than what I use on desktop.
- [x] Manage button has weird behavior with the advanced markdown editor set as default

**Comment by mobitar** [comment]
Generally, there’s only so much we can optimize web-based editors for mobile. These are very complicated editors which really stretch the possibilities of a web browser, let alone a mobile browser. I’d say it’s best to treat web editors on mobile as just a way to view your marked up data, and if absolutely necessary, make minor modifications.

> Manage button has weird behavior with the advanced markdown editor set as default
I assume you mean navigation gets broken? This is fixed in 2.1.33.

**Comment by aaronraimist** [comment]
Yeah I guess the navigation gets broken. I'm on 2.1.33 but I am still experiencing the issue. 

I have the advanced markdown editor set as default and so if I want to tap manage on a note, I wait for the advanced editor to appear so I can dismiss it and then I tap manage but it just changes the manage button to "New Tag" and the manage screen only appears once I leave the note.

**Comment by mobitar** [comment]
When you hit Done on the editor window, does it dismiss with a slide down animation, or no animation, as far as you can tell?

(Bonus points for video recording)

**Comment by aaronraimist** [comment]
No animation, apparently GitHub doesn't support a .mov file so here is a ZIP of a .mov file.
[IMG_9427.zip](https://github.com/standardnotes/mobile/files/1975723/IMG_9427.zip)

**Comment by mobitar** [comment]
Hmm that's annoying. Thought it was fixed with the last release, but I can replicate this myself sometimes, if I press it fast enough. Until I can figure out what's going on the best solution is just wait like 1s after dismissing an editor to hit Manage.

**Comment by aaronraimist** [comment]
Actually I think it is related to how fast you dismiss the editor after opening the note. If you dismiss the editor as soon as you open the note, it will always have this behavior no matter how long you wait after dismissing the editor.

**Comment by mobitar** [comment]
Oh good catch! Didn't realize that. Thanks, this will help.

**Comment by mobitar** [comment]
I believe this was fixed a while ago. Should definitely be in v3.
